# Generated by Django 4.2.11 on 2025-07-09 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mentee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menteeFullName', models.CharField(max_length=255)),
                ('menteeEmail', models.EmailField(max_length=255)),
            ],
        ),
    ]
