# Generated by Django 4.2.11 on 2025-07-09 23:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Mentee',
        ),
    ]
