# Generated by Django 4.2.11 on 2025-07-12 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventsGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('donorFirstName', models.CharField(max_length=255)),
                ('donorLastName', models.CharField(max_length=255)),
                ('donorEmail', models.EmailField(max_length=255)),
                ('donorPhone', models.CharField(max_length=15)),
                ('donorAmount', models.FloatField(max_length=15)),
            ],
        ),
    ]
