# Generated by Django 4.2.11 on 2025-07-13 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_eventsgallery'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mentee',
            name='careerInterest',
        ),
        migrations.RemoveField(
            model_name='mentee',
            name='commentOrMessage',
        ),
        migrations.RemoveField(
            model_name='mentee',
            name='currentSchool',
        ),
        migrations.RemoveField(
            model_name='mentee',
            name='dateOfBirth',
        ),
    ]
