# Generated by Django 4.2.11 on 2025-07-13 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_remove_mentee_careerinterest_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Mentee',
        ),
    ]
