# Generated by Django 4.2.11 on 2025-07-13 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_delete_mentee'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mentee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menteeFirstName', models.CharField(max_length=255)),
                ('menteeLastName', models.CharField(max_length=255)),
                ('menteeEmail', models.EmailField(max_length=255)),
                ('menteePhone', models.CharField(max_length=15)),
                ('parentFirstName', models.CharField(max_length=255)),
                ('parentLastName', models.CharField(max_length=255)),
                ('parentPhone', models.CharField(max_length=15)),
                ('parentEmail', models.EmailField(max_length=255)),
                ('dateOfBirth', models.DateField()),
            ],
        ),
    ]
