# Generated by Django 4.2.11 on 2025-07-13 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_mentee'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Mentee',
        ),
    ]
