# Generated by Django 4.2.11 on 2025-07-13 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_contact_eventsgallery_mentee_mentor'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contact',
        ),
        migrations.DeleteModel(
            name='Mentee',
        ),
        migrations.DeleteModel(
            name='Mentor',
        ),
    ]
