# Generated by Django 4.2.11 on 2025-07-13 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_delete_contact_delete_mentee_delete_mentor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contactFirstName', models.CharField(max_length=255)),
                ('contactLastName', models.CharField(max_length=255)),
                ('contactEmail', models.EmailField(max_length=255)),
                ('contactPhone', models.CharField(max_length=15)),
                ('commentOrMessage', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Mentee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menteeFirstName', models.CharField(max_length=255)),
                ('menteeLastName', models.CharField(max_length=255)),
                ('menteeEmail', models.EmailField(max_length=255)),
                ('menteePhone', models.CharField(max_length=15)),
                ('parentFirstName', models.CharField(max_length=255)),
                ('parentLastName', models.CharField(max_length=255)),
                ('parentPhone', models.CharField(max_length=15)),
                ('parentEmail', models.EmailField(max_length=255)),
                ('dateOfBirth', models.DateField()),
                ('currentSchool', models.CharField(max_length=255)),
                ('careerInterest', models.CharField(max_length=255)),
                ('commentOrMessage', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Mentor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mentorFirstName', models.CharField(max_length=255)),
                ('mentorLastName', models.CharField(max_length=255)),
                ('mentorEmail', models.EmailField(max_length=255)),
                ('mentorPhone', models.CharField(max_length=15)),
                ('mentorProfession', models.CharField(max_length=255)),
                ('mentorResume', models.FileField(upload_to='documents/')),
                ('commentOrMessage', models.TextField()),
            ],
        ),
    ]
