# Generated by Django 4.2.11 on 2025-07-14 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_contact_mentee_mentor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventsgallery',
            name='eventImage1',
            field=models.FileField(blank=True, null=True, upload_to='mediafiles/'),
        ),
        migrations.AlterField(
            model_name='eventsgallery',
            name='eventImage10',
            field=models.FileField(blank=True, null=True, upload_to='mediafiles/'),
        ),
        migrations.AlterField(
            model_name='eventsgallery',
            name='eventImage2',
            field=models.FileField(blank=True, null=True, upload_to='mediafiles/'),
        ),
        migrations.AlterField(
            model_name='eventsgallery',
            name='eventImage3',
            field=models.FileField(blank=True, null=True, upload_to='mediafiles/'),
        ),
        migrations.AlterField(
            model_name='eventsgallery',
            name='eventImage4',
            field=models.FileField(blank=True, null=True, upload_to='mediafiles/'),
        ),
        migrations.AlterField(
            model_name='eventsgallery',
            name='eventImage5',
            field=models.FileField(blank=True, null=True, upload_to='mediafiles/'),
        ),
        migrations.AlterField(
            model_name='eventsgallery',
            name='eventImage6',
            field=models.FileField(blank=True, null=True, upload_to='mediafiles/'),
        ),
        migrations.AlterField(
            model_name='eventsgallery',
            name='eventImage7',
            field=models.FileField(blank=True, null=True, upload_to='mediafiles/'),
        ),
        migrations.AlterField(
            model_name='eventsgallery',
            name='eventImage8',
            field=models.FileField(blank=True, null=True, upload_to='mediafiles/'),
        ),
        migrations.AlterField(
            model_name='eventsgallery',
            name='eventImage9',
            field=models.FileField(blank=True, null=True, upload_to='mediafiles/'),
        ),
    ]
