# Generated by Django 6.0.4 on 2026-04-24 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_alter_eventsgallery_eventimage1_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UpcomingEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('event_date', models.DateField()),
                ('description', models.CharField(blank=True, max_length=255)),
                ('display_order', models.PositiveIntegerField(default=0, help_text='Smaller numbers appear first in the list.')),
                ('is_published', models.BooleanField(default=True, help_text='Uncheck to hide this event from the website without deleting it.')),
            ],
            options={
                'verbose_name': 'Upcoming Event',
                'verbose_name_plural': 'Upcoming Events',
                'ordering': ['display_order', 'event_date', 'title'],
            },
        ),
    ]
